# Generated by Django 5.2.12 on 2026-04-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_attendance_student_dob_student_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
